### ISSUE TITLE
No files being created in /app/config

### ISSUE THREAD

**Issue by samcro1967** [lllllllillllllillll/DweebUI#104]
No files are being created in /app/config.  Every time the container is recreated I have to register as a new user.  Not sure what I am missing.  Below is the docker compose I am using.  The directory does get created.  It is owned by user 1000:1000 on the host and permissions have temporarily been set to 777 to rule them out as the issue.

```
  dweebui:
    hostname: dweebui
    image: lllllllillllllillll/dweebui:latest
    container_name: dweebui
    environment:
      - PORT=8000
      - SECRET=MrWiskers
      - HTTPS=false
    restart: unless-stopped
    ports:
      - 8093:8000
    volumes:
      - ${docker}/dweebui:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by lllllllillllllillll** [comment]
For the latest version (v0.60) you basically end up persisting the entire app in a docker volume. This should work: 

```
version: "3.9"
services:
  dweebui:
    container_name: dweebui
    image: lllllllillllllillll/dweebui
    environment:
      PORT: 8000
      SECRET: MrWiskers
    restart: unless-stopped
    ports:
      - 8093:8000
    volumes:
      - dweebui:/app
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  dweebui:
```

I've resolved this in v0.7X-dev, where you only need to persist the database and the registration secret is configured in the webui under settings: 

`docker run -d --name=DweebUI -p 8093:8000 -v dweebui:/app/database -v /var/run/docker.sock:/var/run/docker.sock lllllllillllllillll/dweebui:v0.7X-dev
`

v0.7X-dev is broken rolling release.
