### ISSUE TITLE
Support for ARM64 in Dockerfile

### ISSUE THREAD

**Issue by kkazakov** [lllllllillllllillll/DweebUI#15]
Please, add more architectures, not only amd64.

**Comment by lllllllillllllillll** [comment]
I'm looking into it.

**Comment by lllllllillllllillll** [comment]
@kkazakov 

I've updated v0.06-dev to be multi-platform, but it's untested: 

```

services:
  dweebui:
    container_name: DweebUI
    image: lllllllillllllillll/dweebui:v0.06-dev
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - cache
    links:
      - cache
    volumes:
      - dweebui:/app
      - caddy:/app/caddyfiles
      - /var/run/docker.sock:/var/run/docker.sock
  cache:
    container_name: DweebCache
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  proxy:
    container_name: DweebProxy
    image: caddy:2.4.5-alpine
    depends_on:
      - dweebui
    restart: unless-stopped
    network_mode: host
    volumes:
      - caddy:/data
      - caddy:/config
      - caddy:/etc/caddy
volumes:
  dweebui:
  cache:
  caddy:
```
