### ISSUE TITLE
Error: Cannot find module '/app/server.js'

### ISSUE THREAD

**Issue by raclariu** [lllllllillllllillll/DweebUI#80]
My Compose
```
  dweebui:
    container_name: dweebui
    image: lllllllillllllillll/dweebui:v0.60
    environment:
      PORT: 8319
      SECRET: MrWiskers
      HTTPS: false
    restart: unless-stopped
    ports:
      - 8319:8000
    volumes:
      - /dkr/config/dweebui:/app
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
```

Cannot connect to gui, logs show me this error
```
Node.js v21.6.2
node:internal/modules/cjs/loader:1152

  throw err;
  ^
Error: Cannot find module '/app/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by lllllllillllllillll** [comment]
Just updated `lllllllillllllillll/dweebui:v0.60-dev`. Let me know if that works.

**Comment by lllllllillllllillll** [comment]
I still need to make changes to persist data. 
You can change it to `- /dkr/config/dweebui:/app/config` or just remove the volume for now.

**Comment by raclariu** [comment]
I've tried with /app/config, still the same. It's something on my end? Is the config wrong in any way? Thanks for looking into it.

**Comment by lllllllillllllillll** [comment]
I've uploaded an image with the 'latest' tag, so the version can get left out now. 

`version: "3.9"
services:
  dweebui:
    container_name: dweebui
    image: lllllllillllllillll/dweebui
    environment:
      PORT: 8000
      SECRET: MrWiskers
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./config:/app/config
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock`
      
      Try deleting the dweebui image and volume. 
      I usually use `docker compose down --rmi all --volumes`

**Comment by lllllllillllllillll** [comment]
related issue: https://github.com/lllllllillllllillll/DweebUI/issues/104

Make sure to use a docker volume instead of a bind mount.

```
version: "3.9"
services:
  dweebui:
    container_name: dweebui
    image: lllllllillllllillll/dweebui
    environment:
      PORT: 8000
      SECRET: MrWiskers
    restart: unless-stopped
    ports:
      - 8093:8000
    volumes:
      - dweebui:/app
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  dweebui:
```
