### ISSUE TITLE
[bug] network tab unavailable

### ISSUE THREAD

**Issue by bingoct** [lllllllillllllillll/DweebUI#87]
saw the image problem in this https://github.com/lllllllillllllillll/DweebUI/issues/85. So i try the dev release. 

## compose.yaml
```yaml
version: "3.9"
services:
  dweebui:
    container_name: dweebui
    image: docker.io/lllllllillllllillll/dweebui:v0.70-dev
    networks:
      - traefik
    environment:
      PORT: ${port}
      SECRET: ${secret}
      HTTPS: false
    volumes:
      - type: bind
        source: ${dockerPath}
        target: /var/run/docker.sock
      - type: volume
        source: dweebui
        target: /app/config
    labels:
      # using traefik to expose service
      # enable traefik
      - traefik.enable=true
networks:
  traefik:
    driver: bridge
    external: true
volumes:
  dweebui:
    external: true
    name: dweebui
```

## Logs
DB Connection: ✔️
Synced Models: ✔️
Listening on http://localhost:8000
file:///app/controllers/networks.js:11
        let network_name = containers[i].HostConfig.NetworkMode;
                                                    ^

TypeError: Cannot read properties of undefined (reading 'NetworkMode')
    at Networks (file:///app/controllers/networks.js:11:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.3.0
DB Connection: ✔️
Synced Models: ✔️
Listening on http://localhost:8000
file:///app/controllers/networks.js:11
        let network_name = containers[i].HostConfig.NetworkMode;
                                                    ^

TypeError: Cannot read properties of undefined (reading 'NetworkMode')
    at Networks (file:///app/controllers/networks.js:11:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.3.0
